services:
  pocketmine:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    ports:
      - "19132:19132/udp"
      - "19133:19133/udp"
    volumes:
      - pocketmine-data:/data
      - pocketmine-plugins:/plugins
    environment:
      POCKETMINE_ARGS: ""

volumes:
  pocketmine-data:
  pocketmine-plugins:
